# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1REUvQTeEC30iD0hukMYBfA1mTtOXsTGk
"""

# Fake News Detection Using NLP

This project aims to build an NLP-powered fake news detection system using machine learning.

## Files

- `Dataset.csv` – Input dataset (must include `text` and `label` columns).
- `sourcedata.py` – Main Python script that trains and evaluates models.
- `read.md` – This file, for project guidance and documentation.

## Setup Instructions

1. Install required packages:
   ```bash
   pip install pandas numpy matplotlib seaborn scikit-learn nltk